# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ostad-assignment-m10"
client_id = "fbf96d060f9abc5e6217c866e9be0ebb"
application_url = "https://nursery-correspondence-heater-accessibility.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nursery-correspondence-heater-accessibility.trycloudflare.com/auth/callback",
  "https://nursery-correspondence-heater-accessibility.trycloudflare.com/auth/shopify/callback",
  "https://nursery-correspondence-heater-accessibility.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "iqbalstore99.myshopify.com"
